FROM python:latest

WORKDIR /pythonapp

COPY . .

CMD ["python", "rng.py"]

#docker build -t pythonapp:v1 .
#docker run -it --name pythonappcontainer pythonapp:v1
#docker stop pythonappcontainer
#docker start -i pythonappcontainer