apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-feedback-vol
  labels:
    app:  my-feedback-app
spec:
  selector:
    matchLabels:
      app: my-vol-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-vol-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  my-feedback-vol
        image:  prajwals06/feedback-app:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: my-feedback-config
              key: APP_PORT
        volumeMounts:
        - mountPath: /data-app/feedback
          name: my-feedback-vol
      volumes:
        - name: my-feedback-vol
          persistentVolumeClaim:
            claimName: my-feedback-pv-claim
          # hostPath:
          #   path: /my-vol-data
          #   type: DirectoryOrCreate
      # volumes:
      #   - name: my-feedback-vol
      #     emptyDir: {}
      # volumes:
      #   - name: localtime
      #     hostPath:
      #       path: /usr/share/zoneinfo/Asia/Shanghai