FROM node

WORKDIR /data-app

COPY package.json /data-app

RUN npm install

COPY . /data-app

ARG DEFAULT_PORT=80

#to create ananymous volume
#VOLUME ["/data-app/node_modules"]
#ENV PORT 80    legacy way
#ENV PORT=80    modern way
ENV PORT $DEFAULT_PORT

EXPOSE $PORT

CMD ["npm", "start"]